"""IoT Device for Stage C Zero-Trust communication.

The IoT Device creates a small sensor-style message and sends it to the Fog
Gateway over TCP. In Stage C, each encrypted message includes a device ID,
timestamp, and nonce for Zero-Trust checks.
"""

import secrets
import socket
import time

from common.network import receive_json, send_json
from common.settings import FOG_PORT, HOST, IOT_SEND_INTERVAL_SECONDS
from crypto.fernet_crypto import IOT_TO_FOG_KEY, encrypt_message


DEVICE_ID = "iot-device-001"


def build_sensor_message() -> dict:
    """Create one beginner-friendly sample IoT message."""

    # The timestamp helps the Fog reject old replayed messages.
    timestamp = int(time.time())

    # The nonce is a random one-time value used to detect repeated messages.
    nonce = secrets.token_hex(16)

    # The payload represents sensor data generated by the IoT device.
    payload = {
        "temperature_celsius": 28.4,
        "humidity_percent": 61,
    }

    # This is the full application message sent to the Fog Gateway.
    return {
        "device_id": DEVICE_ID,
        "message_type": "sensor_reading",
        "timestamp": timestamp,
        "nonce": nonce,
        "payload": payload,
    }


def send_message_to_fog() -> None:
    """Connect to the Fog Gateway and send sensor messages periodically."""

    # Open a TCP client socket from the IoT Device to the Fog Gateway.
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as client_socket:
        client_socket.connect((HOST, FOG_PORT))
        print(f"[IoT] Connected to Fog Gateway at {HOST}:{FOG_PORT}")

        # Keep sending messages until the user stops the program with Ctrl+C.
        while True:
            # Build and send one IoT sensor message.
            message = build_sensor_message()
            print(f"[IoT] Plain message: {message}")

            # Encrypt the message before sending it to the Fog Gateway.
            encrypted_payload = encrypt_message(message, IOT_TO_FOG_KEY)
            encrypted_message = {
                "sender": "iot_device",
                "receiver": "fog_gateway",
                "encryption": "fernet",
                "encrypted_payload": encrypted_payload,
            }
            print(f"[IoT] Sending encrypted message: {encrypted_message}")
            send_json(client_socket, encrypted_message)

            # Wait for the Fog Gateway acknowledgement.
            response = receive_json(client_socket)
            print(f"[IoT] Fog response: {response}")

            # Pause before sending the next reading.
            time.sleep(IOT_SEND_INTERVAL_SECONDS)


if __name__ == "__main__":
    send_message_to_fog()
